### ISSUE TITLE
Configurator UI improvements

### ISSUE THREAD

**Issue by xtreding** [jitsucom/jitsu#244]
## Description
This task contains a couple of tiny bugs/things which we should fix/improve.

### 1. Destinations Mode switcher (`destinations -> Edit any -> Mode`)

![image](https://user-images.githubusercontent.com/18486255/112036372-9bf3f380-8b51-11eb-9077-c3a584752ff1.png)

We should change color or selected button text (black -> white) or change button style (like button with border on https://jitsu.com SignUp button)

![image](https://user-images.githubusercontent.com/18486255/112036506-c47bed80-8b51-11eb-9c3f-c5d599d7f244.png)

### 2. Api Keys Documentation page (`API Keys -> Show integration documentation` ) 

![image](https://user-images.githubusercontent.com/18486255/112063385-63184680-8b72-11eb-925f-41c3e6f64743.png)

- **We should fix infinity loop requests (see network tab)**
- Fix white field in drop-down in right corner
- Fix domains in drop-down and in code fragment (at present there is only `t.jitsu.com`) for selfhosted

### 3. Self hosted sign up page (clone repository and run `docker-compose up` -> `http://localhost:7000`)

![image](https://user-images.githubusercontent.com/18486255/112063937-3fa1cb80-8b73-11eb-88ee-968e213c8c93.png)

- fix `<br>` after `Set up Jitsu` button
- fix white input (it happens while using browser suggestion in input)

### 4. Hover isn't unset in Personal drop-down

![image](https://user-images.githubusercontent.com/18486255/112064700-70cecb80-8b74-11eb-9129-5a40eaa4c542.png)

- Try to click Reset Password -> Cancel modal window -> Open Personal menu one more time
Button must be unhovered after clicking

### 5. Change icon in Facebook marketing source. (Color isn't a good match)

![image](https://user-images.githubusercontent.com/18486255/112064821-a4a9f100-8b74-11eb-9f73-d3adf92d6981.png)

### 6. Source editor

![image](https://user-images.githubusercontent.com/18486255/112065088-1bdf8500-8b75-11eb-9f47-803b5d868f98.png)

- Fix white color
- Remove Table Name field
- Fill Source ID with suggested id by default (like `facebook_marketing1`)
- After saving and clicking `Back to Source list` - source isn't present. (it is coming only after page reload)
- Remove `No Data` text

![image](https://user-images.githubusercontent.com/18486255/112065667-19315f80-8b76-11eb-86ef-4ecf01d51980.png)

![image](https://user-images.githubusercontent.com/18486255/112065346-927c8280-8b75-11eb-9510-0c47c7eb9cbd.png)

- Fix Error After saving such configuration (empty collections)

### 7. Add Modal dialog on `Generate New Key` button with warning about unrevertable changes. (key will be lost)

![image](https://user-images.githubusercontent.com/18486255/112065595-f69f4680-8b75-11eb-82a0-8d1f691175cb.png)

### 8. Change link color of `sources` hint to purple (like everywhere) + make it hovered on hover
![image](https://user-images.githubusercontent.com/18486255/112170165-e59d1680-8c03-11eb-9d3c-747c686860a3.png)

### 9. Table Name and Password aren't required in all destinations. 
![image](https://user-images.githubusercontent.com/18486255/112177527-1122ff80-8c0a-11eb-9f03-ce38f35899ae.png)

**Comment by vklimontovich** [comment]
Current status of the issues:
 - [x] **Destinations Mode switcher (destinations -> Edit any -> Mode)** — colors are not ideal indeed, but marking selection with just border makes things even worse. Anyway, since we're refactoring this form, this component will not be used anywhere (it will be replaced with a dropdown). Let's fix colors next time when we'll use it 
 - [ ] **Api Keys Documentation page** dropdown is fixed, the rest is not
 - [ ] **Self hosted sign up page** spacing is not fixed
 - [ ] **Hover isn't unset in Personal drop-down** to be done
 - [x] **Change icon in Facebook marketing source.** fixed
 - [ ] **Source editor** - fixed
 - [ ] **Add Modal dialog** todo
 - [ ] **Change link color of sources hint to purple (like everywhere) + make it hovered on hover** todo
 - [ ] **Table Name and Password aren't required in all destinations.** — I believe this is going to be fixed with new editor
