### ISSUE TITLE
Documentation publishing 2.0

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#725]
### Problem

At the moment, changes in the documentation are painful. A private `jitsu.com` repo references `jitsu` as a submodule and 
uses `documentation` from there. It raises a few problems:
 - Heavy dependency. jitsu.com downloads all `jitsu` code while it needs only `documentation` folder
 - Git submodules are very counterintuitive and hard to use
 - Not all tools (Vercel as an example) understands git submodules

Also, a few issues make MDX writing painful: we can't use markdown inside JSX components and so on

### Solution

 - Update to MDX 2.0. This release allows to use of markdown inside JSX and introduces a few other improvements; also, we will be able to ditch dynamic imports and do `compile()` on MDX files. This will give us a few options to abandone git submodules
 - jitsu.com should use an external source to get documentation. Preliminary, it could look like this:
   * If `JITSU_DOCUMENTATION_HOME` is set, documentation files should be taken from there. It will be useful for local development and preview. Note: we should make sure that next hot-swap remain functional
   * If `JITSU_DOCUMENTATION_HOME` is not set, the builder should get documentation from public `jitsu` repo (`beta` branch). It could either checkout the repo locally, or download files through HTTP

**Comment by taletski** [comment]
# Notes
Few comments on how the improvements and limitations of the implementation.

#### Improvements
- Documentation development experience. Now you are able to see how your mdx will look like at jitsu.com once deployed.
- No more git submodules because no one loves them.
- No dynamic imports. Users will no longer see loaders because documentation pages are now fully statically built (thanks to `MDX`'s `compile()`).

#### Limitations 
- Documentation files no longer support imports. This is because `MDX`'s `compile()` can only turn them into dynamic imports where a `baseURL` has to be specified which is impossible because those imports are not included into the bundle.
- UI Catalog (`jitsu/configurator/frontend/catalog`) is now shared with `jitsu.com` as an npm package `@jitsu/catalog`. To update the catalog locally when developing `jitsu.com` push your catalog changes to the `beta` branch then wait for `Lerna CI` to publish the new version of `@jitsu/catalog` and install it locally in your `jitsu.com` project. For deployments, `yarn build` will always pre-install the latest version of the catalog package. 

#### Other comments
- Moved contents of `jitsu/documentation/root.json` to `jitsu.com/components/documentation/DocumentationTableOfContents.json` to import it statically.

**Comment by taletski** [comment]
# Catalog as an External Package to Configurator UI

As a part of this task, we extracting the Catalog from the Configurator UI `src` folder into a separate package and link it back to configurator using Lerna.

This will prohibit imports from Configurator UI source code so that Catalog stays tidy and ready to use in `jitsu.com` and other projects.

## Changes

To implement that, the following changes will take place:

### Frontend Folder Structure
The `configurator/frontend` will become a root folder for Lerna. The Configurator UI package code will reside in the `main` folder, while the external packages will live on the same level with it.

Before:
```
jitsu/
├─ configurator/
│  ├─ frontend/
│  │  ├─ src/
│  │  │  ├─ catalog/
│  │  ├─ package.json
```
After:
```
jitsu/
├─ configurator/
│  ├─ frontend/
│  │  ├─ main/
│  │  │  ├─ src/
│  │  │  ├─ package.json
│  │  ├─ catalog/
│  │  │  ├─ package.json
│  │  ├─ lerna.json
│  │  ├─ package.json
```

### First Time Set Up

Run `yarn bootstrap`. It will install all node modules and will symlink the cross-dependencies within the `fontend` folder.

### Developing Locally
Run `yarn start:ui`. The run config (env variables and so on) should remain the same (tested in VSCode).

### Deploying and Publishing to NPM

The new Configurator UI will be deployed once you pushed your changes to `beta` branch. Lerna will also publish a new version of the `catalog` if it detects any changes since the previous tagged commit.

The publishing process will be as follows:
- User pushes to `beta`
- __Vercel__ will build and publish frontend to `cloud.jitsu.com`:
  - run `lerna bootstrap` - that will install all node modules and symlink cross-dependencies
  - run `lerna run build` - that will run `yarn build` in `main`, `catalog` and others. 
  - publish built Configurator UI from `configurator/frontend/main/build`
- __Frontend CI GitHub Action__ will check the code is formatted and valid:
  - run `yarn prettier:check`, `yarn eslint:check`, `lerna run build` in the frontend folder
- __Lerna CI GitHub Action__ will publish the changes in `catalog` and other public packages to npm:
  - run `lerna publish patch --no-private --no-verify-access --yes` in the frontend folder. `patch` will increment the 0.0.x of the versions, `--no-private` is for Lerna not to publish the `main` package, `--no-verify-access` is for Lerna not to ping npm APIs that are not accessible with npm automation tokens.

### Building Docker Image
Will remain the same except for the commands build commands implementation under the hood.
