### ISSUE TITLE
Events Cache performance problem

### ISSUE THREAD

**Issue by absorbb** [jitsucom/jitsu#766]
### Problem

Current events cache implementation is quite heavy and prone to performance or stability problem.
Even if we keep only last 100(capacityPerDestination) events per destination in cache we try to write each event to redis even it is 10000 per second. 
Updating event status is heavy and relies on lua script.

### Possible Solutions

1. Inmemory solution:
Consider simply keeping last `capacityPerDestination` events per destination in memory and using broadcast messages to collect them from all servers. No need to update events. We can use separate collection for statuses and do zipping on backend or frontend.
Only problem that it wont't persist restrarting - but events can be dumped at shutdown

2. Redis solution:
When events cache queue grows big we must not handle every event from it.
drain it to intermediate buffers with capacity=capacityPerDestination. So no more than `capacityPerDestination` events will be written to redis.
Write entire buffer to redis at once.
No need to update record in redis. We can use separate collection for statuses and do zipping on backend or frontend.
That also will allow to get rid of special logic of maintaining capacityPerDestination in redis in favor of simple list collection and LTRIM operation

**Comment by xtreding** [comment]
Discussed implementation:
- Jitsu UI will have 2 sections on `Live Events` page: 
   1. Raw events - last `N` raw JSON events per `API key` sampled with 1 event per second rate. Every raw event JSON contains information about its destination and destination mode.
   2. Processed events - last `N` events (raw JSON + flattened schema + status) per destination sampled with 1 event per second rate.
- Events cache will use Redis lists instead of Redis hash keys
- Events cache API won't have filters by time (`start`, `end`)
- Events cache API will have 1 more endpoint which will return raw events per api key
