### ISSUE TITLE
Add option to retain raw data structure for S3 destination

### ISSUE THREAD

**Issue by johnelbacani** [jitsucom/jitsu#905]
### Problem

When sending data to S3, it is flattened by default. It will be helpful to have an option to retain the raw data structure.

### Solution

Add an option to not apply any transformations.

**Comment by absorbb** [comment]
@johnelbacani 
That is actually a bug. If format is set to "json" flattening shouldn't been applied.
Another bug in documentation indicating that default value for `format` is `json` while in fact it is `flat_json`

Bug is already fixed in `beta` docker images and on https://cloud.jitsu.com.
For standalone versions will be released as a hotfix release shortly.
format must be explicitly set to `json` for s3 destination.
