### ISSUE TITLE
Add abitity to include header data in event

### ISSUE THREAD

**Issue by batalkin** [jitsucom/jitsu#916]
### Summary 
Add abitity to include headers in event

### Problem

Quite often services live behind some reverse proxy. Reverse proxy authenticates a user and send user ID, username maybe some other details a HTTP header downstream. 

```mermaid
graph TD;
    Client-- POST /api/v1/event -->ReveseProxy;
    ReveseProxy-- POST /api/v1/event <br> X-User-ID: 9ab98be1-33e6-44d7-ad59-f6a410a78b6c -->Jitsu;
```

Since we can get user id from the header and trust it, would be great to be able to enrich event details with this id

```yaml
{
   ...event # original event 
   "user": {
      "id": "9ab98be1-33e6-44d7-ad59-f6a410a78b6c"
   }
}
```

### Solution

I am not sure about best approach here. Maybe adding ability to transformations to use request headers is an option. Or narrow this to some fixed set or headers that jitsu will use as override to user details: `X-User-Id`, `X-User-Email`, `X-User-Anonymous-Id`

**Comment by jfk9w** [comment]
Hi, @batalkin!
The feature is ready and available in `beta` Docker image. You may find implementation details in [PR description](https://github.com/jitsucom/jitsu/pull/921). Please note that is mandatory to first upgrade all Jitsu containers before turning on event HTTP context enrichment, otherwise you might get unwanted columns in your destinations.

You can also refer to our [configuration](https://jitsu.com/docs/deployment/deploy-with-docker/joint-image) and [JavaScript transform](https://jitsu.com/docs/configuration/javascript-transform#using-http-headers-in-transformations) documentation sections for details on how to enable and use the feature.
